spring.application.name=FoodyRecommender
server.port=${PORT:8085}
spring.jpa.show-sql=true

# N?p file secret l?y m?t kh?u
spring.config.import=optional:classpath:application-secret.properties

# M?C ??NH CH?Y CH? ?? LOCAL (DEV)
spring.profiles.active=dev