spring.application.name=FoodyRecommender
server.port=8085
spring.jpa.show-sql=true
# Secret password
spring.config.import=optional:classpath:application-secret.properties
# ==============================================================
# 1. C?U HÌNH LOCALHOST (Khi nào ch?y offline thì b? d?u # ? 4 dòng d??i ra)
# ==============================================================
spring.datasource.url=jdbc:mysql://localhost:3306/foodyrecommend
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update

# ==============================================================
# 2. C?U HÌNH CLOUD AIVEN (?ang dùng cái này ?? ??y lên m?ng)
# ==============================================================
#spring.datasource.url=jdbc:mysql://foody-recommender-dbb-ducnghiabachong-foody.l.aivencloud.com:14655/defaultdb?sslMode=REQUIRED
#spring.datasource.username=avnadmin
## M?t kh?u DB ?ã ???c gi?u ?i ?? b?o m?t khi ??y lên GitHub:
#spring.datasource.password=${DB_PASSWORD}
#spring.jpa.hibernate.ddl-auto=update

# ==============================================================
# 3. C?U HÌNH G?I EMAIL GMAIL
# ==============================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ducnghiabachong@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# M?t kh?u ?ng d?ng Mail ?ã ???c gi?u ?i ?? b?o m?t:
spring.mail.password=${MAIL_PASSWORD}